# Generated by Django 5.1.2 on 2024-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('collector', 'Trash Collector'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
