# Generated by Django 5.1.2 on 2024-10-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
