# Generated by Django 5.1.2 on 2024-10-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_generated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
