# Generated by Django 5.1.2 on 2024-10-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_generated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='generated_on',
        ),
    ]
