# Generated by Django 5.1.2 on 2024-10-23 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_generated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
