# Generated by Django 5.1.2 on 2024-10-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_generated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_on',
            field=models.DateTimeField(default=0),
        ),
    ]
